server:
port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:accountsdb
    username: testUser
    password: 
    h2:
      console:
        enabled: true
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

management:
  server:
    port: 8081
  endpoint: 
    health: 
      show-details: always

logging:
  file: logs/account-data-api.log
  pattern:
    file: "%d [%-15.15t] %-5p %-30.30c{1} - %X{mdcData} - %m%n"
  level:
    root: INFO
    com.org.api: INFO

